fix: populate hadolint_output in CI
Ensure that `hadolint_output` is populated in CI and add a e2e test to verify.

Closes: https://github.com/jbergstroem/hadolint-gh-action/issues/147

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -101,3 +101,25 @@ jobs:
             echo "::error::Version mismatch: \"${HADOLINT_VERSION}\" does not equal \"${REQUESTED_VERSION}\""
             exit 1
           fi
+
+  # https://github.com/jbergstroem/hadolint-gh-action/issues/147
+  gh-action-output:
+    name: Action populates output if configured
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./
+        id: action-output
+        with:
+          dockerfile: "test/fixtures/Dockerfile-warning"
+          annotate: false
+          output_format: json
+      - name: Compare output
+        env:
+          OUTPUT: ${{ steps.action-output.outputs.hadolint_output }}
+          ASSERT: '"[{"code":"DL3018","column":1,"file":"test/fixtures/Dockerfile-warning","level":"warning","line":3,"message":"Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`"}]"'
+        run: |
+          if [[ "${OUTPUT}" != "${ASSERT}" ]]; then
+            echo "::error::Output mismatch: \"${OUTPUT}\" does not equal \"${ASSERT}\""
+            exit 1
+          fi
