feat: refactor hadolint version support
- Allow users to pass a specific version of hadolint to action
- Move current hadolint version assignment to action
- Add e2e test to verify functionality
- Fix a bug where `hadolint_version` and `hadolint_output` weren't assigned

Fixes: https://github.com/jbergstroem/hadolint-gh-action/issues/86

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,23 +1,20 @@
 name: test
 on:
   pull_request:
-    paths:
-      - "HADOLINT_VERSION"
-      - "**.sh"
-      - "test/*"
-      - .github/workflows/test.yml
 
 jobs:
   bash_unit:
-    name: bash_unit
+    name: bash tests
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v3.0.2
-      - name: fetch hadolint version
-        run: echo "HADOLINT_VERSION=$(cat HADOLINT_VERSION)" >> "${GITHUB_ENV}"
       - name: install hadolint
+        # yq is like jq for yaml
+        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
         run: |
-          wget -q -O hadolint https://github.com/hadolint/hadolint/releases/download/v${{ env.HADOLINT_VERSION }}/hadolint-Linux-x86_64 && \
+          version="$(yq .inputs.version.default action.yml)" && \
+          echo "::debug::Downloading Hadolint ${{ env.version }}" && \
+          wget -q -O hadolint "https://github.com/hadolint/hadolint/releases/download/v${version}/hadolint-Linux-x86_64" && \
           chmod +x hadolint && \
           sudo mv hadolint /usr/local/bin/hadolint
       - name: install bash_unit
@@ -32,3 +29,29 @@ jobs:
           bash_unit -v
       - name: run suite
         run: bash_unit test/*.sh
+  gh-action-default:
+    name: action validates dockerfiles
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3.0.2
+      - uses: ./
+        with:
+          dockerfile: test/fixtures/Dockerfile-valid
+  gh-action-version:
+    name: action supports custom version
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3.0.2
+      - uses: ./
+        id: check
+        with:
+          dockerfile: test/fixtures/Dockerfile-valid
+          version: 2.9.0
+        env:
+          DEBUG: yes
+      - name: check hadolint version
+        run: |
+          if [[ ! "${{ steps.check.outputs.hadolint_version }}" == "2.9.0-no-git" ]]; then
+            echo "::error::Version mismatch: \"${{ steps.check.outputs.hadolint_version }}\" does not equal \"2.9.0-no-git\""
+            exit 1
+          fi
